### ISSUE TITLE
Can't run .side file

### ISSUE THREAD

**Issue by nikhilvashisht** [SeleniumHQ/selenium-ide#1797]
## 🐛 Bug Report

I have installed selenium-side-runner as per the given instructions on official website. But encounter the following issue whenever I run my .side file. : 

![image](https://github.com/SeleniumHQ/selenium-ide/assets/73426621/0fd4986f-85fc-4203-806d-99d9a96f8d62)

## To Reproduce

No special steps to reproduce this. 

## Expected behavior

The .side file should run as expected. 

## Project file reproducing this issue (highly encouraged)

```
{
  "id": "c724bbd5-c218-434f-93ea-26dc4320e3c1",
  "version": "2.0",
  "name": "download-file",
  "url": "https://arxiv.org",
  "tests": [{
    "id": "7fb8c450-c21f-4483-a5be-01369b383cff",
    "name": "Untitled",
    "commands": [{
      "id": "93666567-0b67-4d95-8d9e-020ad04a15c0",
      "comment": "",
      "command": "open",
      "target": "https://arxiv.org/list/math/new",
      "targets": [],
      "value": ""
    }, {
      "id": "709600ce-3334-44a8-a4cd-ee191606bfdd",
      "comment": "",
      "command": "click",
      "target": "linkText=pdf",
      "targets": [
        ["linkText=pdf", "linkText"],
        ["css=dl:nth-child(10) > dt:nth-child(1) a:nth-child(2)", "css:finder"],
        ["xpath=//a[contains(text(),'pdf')]", "xpath:link"],
        ["xpath=//div[@id='dlpage']/dl/dt/span/a[2]", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/pdf/2402.18580')]", "xpath:href"],
        ["xpath=//span/a[2]", "xpath:position"],
        ["xpath=//a[contains(.,'pdf')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "2efbce68-f681-403c-9f56-a0a984590beb",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["7fb8c450-c21f-4483-a5be-01369b383cff"]
  }],
  "urls": ["https://arxiv.org/"],
  "plugins": []
}
```

## Environment

OS: Windows 11
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.71
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 8.17.0
Only required if using selenium-side-runner
-->
Browser: Brave

**Comment by toddtarsi** [comment]
I would first recommend coming up to Node v16 or greater. I know it said Node v8-10 was supported in the issue template, but Node 8 exceeded end of life almost 5 years ago. I corrected the issue template, so that won't cause confusion anymore.

**Comment by toddtarsi** [comment]
```
(base) ➜  Downloads selenium-side-runner test.side
info: Running test Untitled
info: Building driver for chrome
info: Driver has been built for chrome
info: Finished test Untitled Success
 PASS  ../.nvm/versions/node/v20.11.1/lib/node_modules/selenium-side-runner/dist/main.test.js
  Running project download-file
    Running suite Default Suite
      ✓ Running test Untitled (4613 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.887 s
Ran all test suites within paths ".../node_modules/selenium-side-runner/dist/main.test.js".
```

Yeah, just to confirm, I did get passing output from this. I also see spaces in your user name. If it's still broken on a modern node version, I can try and do some testing around spaces in directory names.

**Comment by nikhilvashisht** [comment]
I tried with node v16.17.0, still getting the same output. I think the issue is with spaces in the directory. How do I fix this? Is there any folder (node / npm) which I can shift to a directory with no spaces?

**Comment by nikhilvashisht** [comment]
I fixed this by moving the npm and npm-cache folder (previously present in AppData/Roaming) to Users directory and changing the environment variables accordingly. Thanks a lot for your help! @toddtarsi

**Comment by toddtarsi** [comment]
Interesting! Thanks for helping me understand @nikhilvashisht
