### ISSUE TITLE
Stored variables in Selenium IDE v3.2.0-beta.1 and selenium-side-runner not working

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#291]
## Meta -
OS:  Windows 10
Selenium IDE Version:  v3.2.0-beta.1
Selenium SIDE Runner Version:   3.2.0-beta.1
Node version:  npm: 5.6.0, node: v8.11.3
Browser:  Chrome

Browser Version:  

## Expected Behavior -
I have stored some variables in Selenium IDE like this:

> execute script **return document.querySelectorAll('some path').length** count

And I am trying to use the stored values like:

> select **id=number** ${count}

And the test workes fine in the IDE, but then I am running it with the selenium-side-runner, and then it fails:

 ` InvalidSelectorError: invalid selector: An invalid or illegal selector was specified

      11 |   await driver.wait(until.elementLocated(By.id("number")));
      12 |   await driver.findElement(By.id("number")).then(element => {
    > 13 |     element.findElement(By.css("*[value=${vars.count}]")).then(option => {
         |             ^
      14 |       option.click();
      15 |     });
      16 |   });
`

Why is this wrong? How should I use stores variables?

## Actual Behavior -
Should be the same result trough the IDE and the selenium-side-runner ?

**Comment by corevo** [comment]
You aren't using the latest version of the runner, get it via.  
`npm install selenium-side-runner@beta -g`.  
The problem exists there too, and will fix it.

**Comment by cemol** [comment]
OK, I wrote wrong, i am using selenium-side-runner version 3.2.0-beta.1.
Thanks :) When do you think you will fix the problem?

**Comment by corevo** [comment]
Can you confirm that the issue is resolved?

**Comment by cemol** [comment]
The same problem still exists, but shall I update something?

**Comment by corevo** [comment]
I pushed a fix for it in the 3rd beta, make sure to load and save the project file again using the IDE.

**Comment by cemol** [comment]
Still not work :/ 

```
TypeError: Assignment to constant variable.

      13 | });
      14 | beforeEach(() => {
    > 15 |   vars = {};
         |   ^
      16 | });
      17 | afterEach(async () => (cleanup()));

      at Object.<anonymous>.beforeEach (EBudBok_div.test.js:15:3)
```


```
    InvalidSelectorError: invalid selector: Unable to locate an element with the xpath expression //*.../a[${vars.down}] because of the following error:
    SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*.../a[${vars.down}]' is not a valid XPath expression.
      (Session info: chrome=67.0.3396.99)
      (Driver info: chromedriver=2.40.565498 (...),platform=Windows NT 10.0.16299 x86_64)

      383 |   vars["finish_time_down"] = await driver.executeScript(`return document.querySelector('#FinishTime').innerText `);
      384 |   vars["down"] = "2";
    > 385 |   await driver.wait(until.elementLocated(By.xpath("//*.../a[${vars.down}]")));
          |                ^
      386 |   await driver.findElement(By.xpath("//*.../a[${vars.down}]")).then(element => {
      387 |     driver.actions().click(element).perform();
      388 |   });
```

**Comment by cemol** [comment]
<img width="375" alt="1" src="https://user-images.githubusercontent.com/40626045/42810390-1b06eb8a-89b8-11e8-96bc-aaab071edf64.PNG">

This does not work

**Comment by cemol** [comment]
What do you mean by using `beta.1`? Im using:
selenium-side-runner --version -> `3.2.0-beta.3`

**Comment by corevo** [comment]
You need to load the project and save it again using the 3rd beta of the IDE not the runner.

**Comment by cemol** [comment]
Oh, I see, where is the link to the 3rd beta of the IDE? :)

**Comment by cemol** [comment]
My html (dropdown):
```
<select name="name" id="road">
    <option style="display:none"></option>
        <option value="1">
            301
        </option>
        <option value="2">
            302
        </option>
 </select>
```

My IDE command:
```
store 302 id
select id=road ${id}
```

This workes then playback through the IDE
