### ISSUE TITLE
Win10 selenium-side-runner won't take chromeOptions.args

### ISSUE THREAD

**Issue by yzliu** [SeleniumHQ/selenium-ide#793]
## 🐛 Bug Report

I tried to use `chromeOptions.args=[...]` to configure `selenium-side-runner`, originally for `user-data-dir`. But it seems like nothing in the `[...]` is honered.

## To Reproduce

Try tesing some arguments, say `'incognito'` and `'start-maximized'`:

`selenium-side-runner -c "browserName=chrome chromeOptions.args=[incognito, start-maximized]" test.side`

A half-sized normal Chrome browser was opened.

## Expected behavior

I expected a maximized incognito Chrome window created.

## Environment

OS: Windows 10 64bit
Selenium IDE Version:  3.12.0
Selenium SIDE Runner Version:  3.12.1
Node version: 10.16.3
chromedirver: 76.0.3809.126

**Comment by tourdedave** [comment]
@yzliu try placing `goog:` in front of chromeOption (e.g., `goog:chromeOptions`).

**Comment by yzliu** [comment]
Worked! Many thanks!

**Comment by tourdedave** [comment]
You're welcome! We've updated the docs to show this. Just waiting on the deployment to go through.

**Comment by yzliu** [comment]
Seems like `--config-file` doesn't work the same way. The following YAML file is still not working, with or without `goog:`:

```
capabilities:
  browserName: 'chrome'
  goog:chromeOptions:
    args:
      [start-maximized]
```

**Comment by corevo** [comment]
This yml is invalid try:
```yaml
capabilities:
  browserName: 'chrome'
  goog:chromeOptions:
    args:
      - start-maximized
```
